### ISSUE TITLE
Spacing issue on match call

### ISSUE THREAD

**Issue by fredck** [pjasiun/fuma#53]
When a match is called, this is the way it is presented:

```
@a.kruszewski @pjasiun :red_circle: (10 : 9.72)  :large_blue_circle:@maciek-k @kkrzton
```

There are spacing issues around `:large_blue_circle:`.

**Comment by jodator** [comment]
@fredck: thanks for reporting. Already fixed on master: https://github.com/pjasiun/fuma/commit/021fd3124df9c1b6d0f4e9a98fd843fb1d7aa722

**Comment by fredck** [comment]
Cool... in fact I was checking master and didn't understand how the hell it is wrong :D
