### ISSUE TITLE
`/fb +` and `/fb -` commands

### ISSUE THREAD

**Issue by fredck** [pjasiun/fuma#6]
There should be an easy way to setup a match. I have this proposal:
1. Interested player runs `/fb`
   - The player gets assigned to the next available match.
   - The player gets a feedback message: "You're joining the next match!".
   - The channels gets a message: "A new player joined the next match! Waiting for the next 3 souls. Go for it!".
2. Assigned player runs `/fb -1`
   - The player is removed from the current match.
   - The player gets a feedback message: ":chicken:"
   - The channel gets a message: "One of the players resigned (:chicken:). Now we need 4 players again. Time to join it!".
3. All 4 slots assigned!
   - The server calculates the teams setup.
   - The channel gets a message with the team setup and expected result (rounded!): ":fire: @playerA @playerB 10 : 8 @playerC @playerD - gogogo!"
   - A new match starts on the server.

**Comment by pjasiun** [comment]
:+1: 

I was thinking recently about:
`/fb +` to assigned myself
`/fb + @user` to add someone else (it's a common case in fact)
`/fb -` to be a :chicken: 
`/fb - @user` someone else need to go, be a :chicken:

**Comment by pjasiun** [comment]
And I would be more then happy accepting a PR ;)

**Comment by mlewand** [comment]
> I was thinking about:
> /fb + to assigned myself
> /fb + @user to add someone else (it's a common case in fact)
> /fb - to be a  
> /fb - @user someone else need to go be a

Yea it looks nice. And you should be able to register multiple users, e.g. `/fb + @user1 @user2 @user3`

**Comment by fredck** [comment]
+1

With feedback "Tell @user that s/he's a :chicken:" :D

**Comment by pjasiun** [comment]
> Yea it looks nice. And you should be able to register multiple users, e.g. /fb + @user1 @user2 @user3

:+1: 

> With feedback "Tell @user that s/he's a :chicken:" :D

:+1: 

Why we are not able to agree about the API in other projects that fast? ;)

**Comment by fredck** [comment]
> And I would be more then happy accepting a PR ;)

I did my job already as the Business Development Lead Link :D and @mlewand is afraid of this feature, so don't count on him.

**Comment by jodator** [comment]
+1 from as @pjasiun described with +/-

**Comment by pjasiun** [comment]
Follow-ups: #21, #22, #23, #24.
