### ISSUE TITLE
Do not show players who played less then 20 games in the rank

### ISSUE THREAD

**Issue by pjasiun** [pjasiun/fuma#8]
Score of players who played less then 20 games is unreliable. It should be skipped in the rank.

But there should be the way to check the score for such player, so new command `/fb score` may be introduced, or the player who asked for the rank should be additionally displayed below the table.

**Comment by fredck** [comment]
Maybe `/fb rank` can show both the "Pro League" and "Amateur League" (those with less than 20 matches).

**Comment by pjasiun** [comment]
I was also thinking about it, but "Amateur League" will contains 1-3 people with the random score. I would call them `Newcommers` or `Come ups`.

**Comment by jodator** [comment]
@pjasiun or `noobs`

**Comment by fredck** [comment]
Just remembered the right name for them: `Rookies` - https://en.wikipedia.org/wiki/Rookie ;)
